# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_pb2 as rpc__pb2


class ShareManagerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShareCreate = channel.unary_unary(
        '/ShareManagerService/ShareCreate',
        request_serializer=rpc__pb2.ShareCreateRequest.SerializeToString,
        response_deserializer=rpc__pb2.ShareResponse.FromString,
        )
    self.ShareDelete = channel.unary_unary(
        '/ShareManagerService/ShareDelete',
        request_serializer=rpc__pb2.ShareDeleteRequest.SerializeToString,
        response_deserializer=rpc__pb2.ShareResponse.FromString,
        )
    self.ShareGet = channel.unary_unary(
        '/ShareManagerService/ShareGet',
        request_serializer=rpc__pb2.ShareGetRequest.SerializeToString,
        response_deserializer=rpc__pb2.ShareResponse.FromString,
        )
    self.ShareList = channel.unary_unary(
        '/ShareManagerService/ShareList',
        request_serializer=rpc__pb2.ShareListRequest.SerializeToString,
        response_deserializer=rpc__pb2.ShareListResponse.FromString,
        )
    self.ShareWatch = channel.unary_stream(
        '/ShareManagerService/ShareWatch',
        request_serializer=rpc__pb2.ShareWatchRequest.SerializeToString,
        response_deserializer=rpc__pb2.ShareResponse.FromString,
        )
    self.LogWatch = channel.unary_stream(
        '/ShareManagerService/LogWatch',
        request_serializer=rpc__pb2.LogWatchRequest.SerializeToString,
        response_deserializer=rpc__pb2.LogResponse.FromString,
        )
    self.VersionGet = channel.unary_unary(
        '/ShareManagerService/VersionGet',
        request_serializer=rpc__pb2.VersionRequest.SerializeToString,
        response_deserializer=rpc__pb2.VersionResponse.FromString,
        )


class ShareManagerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShareCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShareDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShareGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShareList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShareWatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LogWatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VersionGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShareManagerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShareCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ShareCreate,
          request_deserializer=rpc__pb2.ShareCreateRequest.FromString,
          response_serializer=rpc__pb2.ShareResponse.SerializeToString,
      ),
      'ShareDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ShareDelete,
          request_deserializer=rpc__pb2.ShareDeleteRequest.FromString,
          response_serializer=rpc__pb2.ShareResponse.SerializeToString,
      ),
      'ShareGet': grpc.unary_unary_rpc_method_handler(
          servicer.ShareGet,
          request_deserializer=rpc__pb2.ShareGetRequest.FromString,
          response_serializer=rpc__pb2.ShareResponse.SerializeToString,
      ),
      'ShareList': grpc.unary_unary_rpc_method_handler(
          servicer.ShareList,
          request_deserializer=rpc__pb2.ShareListRequest.FromString,
          response_serializer=rpc__pb2.ShareListResponse.SerializeToString,
      ),
      'ShareWatch': grpc.unary_stream_rpc_method_handler(
          servicer.ShareWatch,
          request_deserializer=rpc__pb2.ShareWatchRequest.FromString,
          response_serializer=rpc__pb2.ShareResponse.SerializeToString,
      ),
      'LogWatch': grpc.unary_stream_rpc_method_handler(
          servicer.LogWatch,
          request_deserializer=rpc__pb2.LogWatchRequest.FromString,
          response_serializer=rpc__pb2.LogResponse.SerializeToString,
      ),
      'VersionGet': grpc.unary_unary_rpc_method_handler(
          servicer.VersionGet,
          request_deserializer=rpc__pb2.VersionRequest.FromString,
          response_serializer=rpc__pb2.VersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ShareManagerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
