# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\trpc.proto\"$\n\x12ShareCreateRequest\x12\x0e\n\x06volume\x18\x01 \x01(\t\"$\n\x12ShareDeleteRequest\x12\x0e\n\x06volume\x18\x01 \x01(\t\"!\n\x0fShareGetRequest\x12\x0e\n\x06volume\x18\x01 \x01(\t\"\x13\n\x11ShareWatchRequest\"P\n\rShareResponse\x12\x0e\n\x06volume\x18\x01 \x01(\t\x12\x11\n\texport_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x12\n\x10ShareListRequest\"\x82\x01\n\x11ShareListResponse\x12.\n\x06shares\x18\x01 \x03(\x0b\x32\x1e.ShareListResponse.SharesEntry\x1a=\n\x0bSharesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.ShareResponse:\x02\x38\x01\"\x11\n\x0fLogWatchRequest\"\x1b\n\x0bLogResponse\x12\x0c\n\x04line\x18\x02 \x01(\t\"\x10\n\x0eVersionRequest\"s\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x11\n\tgitCommit\x18\x02 \x01(\t\x12\x11\n\tbuildDate\x18\x03 \x01(\t\x12\x12\n\napiVersion\x18\x04 \x01(\x03\x12\x15\n\rapiMinVersion\x18\x05 \x01(\x03\x32\xfe\x02\n\x13ShareManagerService\x12\x34\n\x0bShareCreate\x12\x13.ShareCreateRequest\x1a\x0e.ShareResponse\"\x00\x12\x34\n\x0bShareDelete\x12\x13.ShareDeleteRequest\x1a\x0e.ShareResponse\"\x00\x12.\n\x08ShareGet\x12\x10.ShareGetRequest\x1a\x0e.ShareResponse\"\x00\x12\x34\n\tShareList\x12\x11.ShareListRequest\x1a\x12.ShareListResponse\"\x00\x12\x34\n\nShareWatch\x12\x12.ShareWatchRequest\x1a\x0e.ShareResponse\"\x00\x30\x01\x12.\n\x08LogWatch\x12\x10.LogWatchRequest\x1a\x0c.LogResponse\"\x00\x30\x01\x12/\n\nVersionGet\x12\x0f.VersionRequest\x1a\x10.VersionResponseb\x06proto3')
)




_SHARECREATEREQUEST = _descriptor.Descriptor(
  name='ShareCreateRequest',
  full_name='ShareCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='ShareCreateRequest.volume', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=49,
)


_SHAREDELETEREQUEST = _descriptor.Descriptor(
  name='ShareDeleteRequest',
  full_name='ShareDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='ShareDeleteRequest.volume', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=87,
)


_SHAREGETREQUEST = _descriptor.Descriptor(
  name='ShareGetRequest',
  full_name='ShareGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='ShareGetRequest.volume', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=122,
)


_SHAREWATCHREQUEST = _descriptor.Descriptor(
  name='ShareWatchRequest',
  full_name='ShareWatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=143,
)


_SHARERESPONSE = _descriptor.Descriptor(
  name='ShareResponse',
  full_name='ShareResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='ShareResponse.volume', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='export_id', full_name='ShareResponse.export_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='ShareResponse.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='ShareResponse.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=225,
)


_SHARELISTREQUEST = _descriptor.Descriptor(
  name='ShareListRequest',
  full_name='ShareListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=245,
)


_SHARELISTRESPONSE_SHARESENTRY = _descriptor.Descriptor(
  name='SharesEntry',
  full_name='ShareListResponse.SharesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ShareListResponse.SharesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ShareListResponse.SharesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=378,
)

_SHARELISTRESPONSE = _descriptor.Descriptor(
  name='ShareListResponse',
  full_name='ShareListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shares', full_name='ShareListResponse.shares', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SHARELISTRESPONSE_SHARESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=378,
)


_LOGWATCHREQUEST = _descriptor.Descriptor(
  name='LogWatchRequest',
  full_name='LogWatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=397,
)


_LOGRESPONSE = _descriptor.Descriptor(
  name='LogResponse',
  full_name='LogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='LogResponse.line', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=426,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=444,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gitCommit', full_name='VersionResponse.gitCommit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildDate', full_name='VersionResponse.buildDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='VersionResponse.apiVersion', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apiMinVersion', full_name='VersionResponse.apiMinVersion', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=561,
)

_SHARELISTRESPONSE_SHARESENTRY.fields_by_name['value'].message_type = _SHARERESPONSE
_SHARELISTRESPONSE_SHARESENTRY.containing_type = _SHARELISTRESPONSE
_SHARELISTRESPONSE.fields_by_name['shares'].message_type = _SHARELISTRESPONSE_SHARESENTRY
DESCRIPTOR.message_types_by_name['ShareCreateRequest'] = _SHARECREATEREQUEST
DESCRIPTOR.message_types_by_name['ShareDeleteRequest'] = _SHAREDELETEREQUEST
DESCRIPTOR.message_types_by_name['ShareGetRequest'] = _SHAREGETREQUEST
DESCRIPTOR.message_types_by_name['ShareWatchRequest'] = _SHAREWATCHREQUEST
DESCRIPTOR.message_types_by_name['ShareResponse'] = _SHARERESPONSE
DESCRIPTOR.message_types_by_name['ShareListRequest'] = _SHARELISTREQUEST
DESCRIPTOR.message_types_by_name['ShareListResponse'] = _SHARELISTRESPONSE
DESCRIPTOR.message_types_by_name['LogWatchRequest'] = _LOGWATCHREQUEST
DESCRIPTOR.message_types_by_name['LogResponse'] = _LOGRESPONSE
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareCreateRequest = _reflection.GeneratedProtocolMessageType('ShareCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHARECREATEREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareCreateRequest)
  })
_sym_db.RegisterMessage(ShareCreateRequest)

ShareDeleteRequest = _reflection.GeneratedProtocolMessageType('ShareDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHAREDELETEREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareDeleteRequest)
  })
_sym_db.RegisterMessage(ShareDeleteRequest)

ShareGetRequest = _reflection.GeneratedProtocolMessageType('ShareGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHAREGETREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareGetRequest)
  })
_sym_db.RegisterMessage(ShareGetRequest)

ShareWatchRequest = _reflection.GeneratedProtocolMessageType('ShareWatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHAREWATCHREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareWatchRequest)
  })
_sym_db.RegisterMessage(ShareWatchRequest)

ShareResponse = _reflection.GeneratedProtocolMessageType('ShareResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHARERESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareResponse)
  })
_sym_db.RegisterMessage(ShareResponse)

ShareListRequest = _reflection.GeneratedProtocolMessageType('ShareListRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHARELISTREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareListRequest)
  })
_sym_db.RegisterMessage(ShareListRequest)

ShareListResponse = _reflection.GeneratedProtocolMessageType('ShareListResponse', (_message.Message,), {

  'SharesEntry' : _reflection.GeneratedProtocolMessageType('SharesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SHARELISTRESPONSE_SHARESENTRY,
    '__module__' : 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:ShareListResponse.SharesEntry)
    })
  ,
  'DESCRIPTOR' : _SHARELISTRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ShareListResponse)
  })
_sym_db.RegisterMessage(ShareListResponse)
_sym_db.RegisterMessage(ShareListResponse.SharesEntry)

LogWatchRequest = _reflection.GeneratedProtocolMessageType('LogWatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGWATCHREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:LogWatchRequest)
  })
_sym_db.RegisterMessage(LogWatchRequest)

LogResponse = _reflection.GeneratedProtocolMessageType('LogResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:LogResponse)
  })
_sym_db.RegisterMessage(LogResponse)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)


_SHARELISTRESPONSE_SHARESENTRY._options = None

_SHAREMANAGERSERVICE = _descriptor.ServiceDescriptor(
  name='ShareManagerService',
  full_name='ShareManagerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=564,
  serialized_end=946,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShareCreate',
    full_name='ShareManagerService.ShareCreate',
    index=0,
    containing_service=None,
    input_type=_SHARECREATEREQUEST,
    output_type=_SHARERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShareDelete',
    full_name='ShareManagerService.ShareDelete',
    index=1,
    containing_service=None,
    input_type=_SHAREDELETEREQUEST,
    output_type=_SHARERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShareGet',
    full_name='ShareManagerService.ShareGet',
    index=2,
    containing_service=None,
    input_type=_SHAREGETREQUEST,
    output_type=_SHARERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShareList',
    full_name='ShareManagerService.ShareList',
    index=3,
    containing_service=None,
    input_type=_SHARELISTREQUEST,
    output_type=_SHARELISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShareWatch',
    full_name='ShareManagerService.ShareWatch',
    index=4,
    containing_service=None,
    input_type=_SHAREWATCHREQUEST,
    output_type=_SHARERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LogWatch',
    full_name='ShareManagerService.LogWatch',
    index=5,
    containing_service=None,
    input_type=_LOGWATCHREQUEST,
    output_type=_LOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VersionGet',
    full_name='ShareManagerService.VersionGet',
    index=6,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHAREMANAGERSERVICE)

DESCRIPTOR.services_by_name['ShareManagerService'] = _SHAREMANAGERSERVICE

# @@protoc_insertion_point(module_scope)
