# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08sm.proto\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x16\x46ilesystemTrimResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2Z\n\x13ShareManagerService\x12\x43\n\x0e\x46ilesystemTrim\x12\x16.google.protobuf.Empty\x1a\x17.FilesystemTrimResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_FILESYSTEMTRIMRESPONSE = _descriptor.Descriptor(
  name='FilesystemTrimResponse',
  full_name='FilesystemTrimResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='FilesystemTrimResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['FilesystemTrimResponse'] = _FILESYSTEMTRIMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilesystemTrimResponse = _reflection.GeneratedProtocolMessageType('FilesystemTrimResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILESYSTEMTRIMRESPONSE,
  '__module__' : 'sm_pb2'
  # @@protoc_insertion_point(class_scope:FilesystemTrimResponse)
  })
_sym_db.RegisterMessage(FilesystemTrimResponse)



_SHAREMANAGERSERVICE = _descriptor.ServiceDescriptor(
  name='ShareManagerService',
  full_name='ShareManagerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='FilesystemTrim',
    full_name='ShareManagerService.FilesystemTrim',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FILESYSTEMTRIMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHAREMANAGERSERVICE)

DESCRIPTOR.services_by_name['ShareManagerService'] = _SHAREMANAGERSERVICE

# @@protoc_insertion_point(module_scope)
