#!/bin/bash
set -e

source $(dirname $0)/version

LINKFLAGS="-X main.Version=$VERSION
           -X main.GitCommit=$GITCOMMIT
           -X main.BuildDate=$BUILDDATE
           -extldflags -static -s"

cd $(dirname $0)/..

mkdir -p bin
archs=("amd64" "arm64")
for arch in "${archs[@]}"; do
    CGO_ENABLED=0 GOARCH="$arch" go build -o "bin/longhorn-share-manager-$arch" -ldflags "$LINKFLAGS"
done
