#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PROJECT=`basename "$PWD"`

if [ ! -x ./bin/longhorn ]; then
    ./scripts/build
fi

cp -r bin package/

arch=$(uname -m)
if [ "$arch" == "aarch64" ]; then
    ARCH="arm64"
else
    ARCH="amd64"
fi
APIVERSION=`./bin/longhorn-share-manager-"$ARCH" version --client-only|jq ".clientVersion.apiVersion"`

TAG=${TAG:-"v${APIVERSION}_`date -u +%Y%m%d`"}
REPO=${REPO:-longhornio}
IMAGE=${REPO}/${PROJECT}:${TAG}

# update base image to get latest changes
BASE_IMAGE=`grep FROM package/Dockerfile | grep -v AS | awk '{print $2}'`
docker pull ${BASE_IMAGE}

echo "Building image ${IMAGE} based on ${BASE_IMAGE} with ARCH=${ARCH} SRC_BRANCH=${SRC_BRANCH} SRC_TAG=${SRC_TAG}"
buildx build \
  --load \
  --build-arg ARCH="${ARCH}" \
  --build-arg SRC_BRANCH="${SRC_BRANCH}" \
  --build-arg SRC_TAG="${SRC_TAG}" \
  -t "${IMAGE}" \
  -f package/Dockerfile .

echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_image
